name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Authenticate with npm registry
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm login --registry=https://registry.npmjs.org/ --scope=@flrfinance --always-auth

      - name: Build and test
        run: npm run build && npm test

      - name: Publish package
        if: github.ref == 'refs/tags/v*'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
